parameters:
  toolchain: 'nightly'
  vmImage: 'ubuntu-16.04'
  name: ''

jobs:
- job: ${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.vmImage }}
  steps:
    - template: azure-install-rust.yml
      parameters:
        toolchain: ${{ parameters.toolchain }}
    - script: cargo test -vv --all --target ${{ parameters.target }}
    - script: cargo test -vv --all --release --target ${{ parameters.target }}
    - script: cargo test -vv --all --target ${{ parameters.target }} --features=unstable
    - script: cargo test -vv --all --release --target ${{ parameters.target }} --features=unstable
